from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from oauth2client.service_account import ServiceAccountCredentials



# Documentation: https://pythonhosted.org/PyDrive/filelist.html

# the 'service_account_pem.json' is generated by GCP Dev and contains the public Key used this specific method...
# the APP must be authorized by Google Drive user to access the content... by the way, all files uploaded here will go to a Virtual Google Drive, and will use API quotas
def useServiceAccount(): 

	_SCOPE_ = [
		'https://www.googleapis.com/auth/drive',
	]

	gauth = GoogleAuth()
	gauth.auth_method = 'service'
	gauth.credentials = ServiceAccountCredentials.from_json_keyfile_name('service_account_pem.json', _SCOPE_)
	# gauth.LocalWebserverAuth() # not used here

	drive = GoogleDrive(gauth)

	##########################
	# Doc params: https://developers.google.com/drive/api/v2/search-files#query_string_examples
	file_list = drive.ListFile(
	    {
	        'q': "'root' in parents",
	        # 'driveId': "<ID_drive_shared>",
	        # 'corpora': "drive",
	        'supportsAllDrives': True,
	        'includeItemsFromAllDrives': True,
	    }
	).GetList()

	for file in file_list:
	    print('title: %s, id: %s, altLink: %s' % (file['title'], file['id'], file['alternateLink']))


	# # UPLOAD TEST:
	# # #################
	# file1 = drive.CreateFile({
	# 			'title': 'hello.txt',
	# 		})
	# file1.SetContentString('hello')
	# file1.Upload() # Files.insert()




def useWebserverAuth():

	gauth = GoogleAuth() 
	gauth.LocalWebserverAuth() # use the 'settings.yaml' config file, and create a 'credentials' to auth

	drive = GoogleDrive(gauth)

	##########################
	# Doc params: https://developers.google.com/drive/api/v2/search-files#query_string_examples
	file_list = drive.ListFile(
	    {
	        'q': "'root' in parents",
	        # 'driveId': "<ID_drive_shared>",
	        # 'corpora': "drive",
	        'supportsAllDrives': True,
	        'includeItemsFromAllDrives': True,
	    }
	).GetList()

	for file in file_list:
	    print('title: %s, id: %s, altLink: %s' % (file['title'], file['id'], file['alternateLink']))

